// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCO8jRz7urRrTCJhlJWIpvpq2uMU553Gs',
    appId: '1:868869888441:web:ef3f0f40e568ee068a7e68',
    messagingSenderId: '868869888441',
    projectId: 'memoralife-1d316',
    authDomain: 'memoralife-1d316.firebaseapp.com',
    storageBucket: 'memoralife-1d316.appspot.com',
    measurementId: 'G-FYX73WVHGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6z-cCZFFj69brjVs6ilMz7-zE7ikNtHM',
    appId: '1:868869888441:android:b66f866597f2ad188a7e68',
    messagingSenderId: '868869888441',
    projectId: 'memoralife-1d316',
    storageBucket: 'memoralife-1d316.appspot.com',
  );
}
